networks:
  go

services:

  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bankdon40
      POSTGRES_DB: nutchapholshop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:var/lib/postgresql/postgres_data

volumes:
  postgres_data:




